/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flightsim_fsuipc_fsuipc_0005fwrapper */

#ifndef _Included_com_flightsim_fsuipc_fsuipc_0005fwrapper
#define _Included_com_flightsim_fsuipc_fsuipc_0005fwrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flightsim_fsuipc_fsuipc_0005fwrapper
 * Method:    Open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_flightsim_fsuipc_fsuipc_1wrapper_Open
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_flightsim_fsuipc_fsuipc_0005fwrapper
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flightsim_fsuipc_fsuipc_1wrapper_Close
  (JNIEnv *, jclass);

/*
 * Class:     com_flightsim_fsuipc_fsuipc_0005fwrapper
 * Method:    ReadData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_flightsim_fsuipc_fsuipc_1wrapper_ReadData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_flightsim_fsuipc_fsuipc_0005fwrapper
 * Method:    WriteData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_flightsim_fsuipc_fsuipc_1wrapper_WriteData
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_flightsim_fsuipc_fsuipc_0005fwrapper
 * Method:    Process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flightsim_fsuipc_fsuipc_1wrapper_Process
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
